In [ ]:
1. 文件读取 
2. 特征提取
3. 分类算法，svm,RF,
4. 绘图PR，AUC，训练曲线与测试曲线，学习曲线与验证曲线
5. 指标acc,presion,recall,自定义的误判率和漏判率

In [1]:
from sklearn.feature_extraction import DictVectorizer
# 将dict转成numpy。采用了对同一个key采用了ont-hot，数值型values保留原类型
measurements = [
    {'city': 'Dubai', 'temperature': 33.},
    {'city': 'London', 'temperature': 12.},
    {'city': 'San Francisco', 'temperature': 18.},
] 

vec = DictVectorizer()
print(vec.fit_transform(measurements).toarray(), '\n')
print('city有三个字符型的值，one-hot后有三列;temperature数值型，保留，所以共有4列','\n')
print(vec.get_feature_names(), '\n')
print('通过此方法获得one-hot后，每列所对应的原本的值')

[[ 1.  0.  0. 33.]
 [ 0.  1.  0. 12.]
 [ 0.  0.  1. 18.]] 

city有三个字符型的值，one-hot后有三列;temperature数值型，保留，所以共有4列 

['city=Dubai', 'city=London', 'city=San Francisco', 'temperature'] 

通过此方法获得one-hot后，每列所对应的原本的值


# from sklearn.feature_extraction.text import CountVectorizer
- 实现了 tokenization （词语切分,包括n-gram）和 occurrence counting （出现频数统计）,TF-IDF
- 这个模型有很多参数，但参数的默认初始值是相当合理的。查看文档获取

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
# 实现了 tokenization （词语切分,包括n-gram,停用词）和 occurrence counting （出现频数统计）,TF-IDF
# 这个模型有很多参数，但参数的默认初始值是相当合理的。查看文档获取

In [3]:
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]

In [4]:
vectorizer = CountVectorizer()
#bigram_vectorizer = CountVectorizer(ngram_range=(1, 2),
#                                    token_pattern=r'\b\w+\b', min_df=1) # 提取n-gram
X = vectorizer.fit_transform(corpus)
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [5]:
X.toarray() # 词袋结果, 注意第二行有个2 ，说明了该方法是统计了词频的

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [6]:
vectorizer.vocabulary_ # 查看单词对应索引
vectorizer.vocabulary_.get('xxx') # 指定获取某一单词的所有

# TfidfTransformer

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer

In [8]:
transformer = TfidfTransformer(smooth_idf=False)

counts = [[3, 0, 1],
          [2, 0, 0],
          [3, 0, 0],
          [4, 0, 0],
          [3, 2, 0],
          [3, 0, 2]]

tfidf = transformer.fit_transform(counts)
tfidf.toarray() 

array([[0.81940995, 0.        , 0.57320793],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.47330339, 0.88089948, 0.        ],
       [0.58149261, 0.        , 0.81355169]])

# TfidfVectorizer

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
# 它将 CountVectorizer 和 TfidfTransformer 的所有选项组合在一个单例模型中
vectorizer = TfidfVectorizer()

corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]

vectorizer.fit_transform(corpus).toarray()

array([[0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674],
       [0.        , 0.27230147, 0.        , 0.27230147, 0.        ,
        0.85322574, 0.22262429, 0.        , 0.27230147],
       [0.55280532, 0.        , 0.        , 0.        , 0.55280532,
        0.        , 0.28847675, 0.55280532, 0.        ],
       [0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674]])

# SVM

In [30]:
from sklearn import svm

X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC(C=1.0)
clf.fit(X, y)
clf.predict([[2., 2.]])

array([1])

In [ ]:
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [1]:
import os  
      
def file_name(file_dir):   
    for root, dirs, files in os.walk(file_dir):  
        #print(root) #当前目录路径  
        #print(dirs) #当前路径下所有子目录  
        return files #当前路径下所有非目录子文件

In [2]:
list_fileName_neg = file_name('./dataSet/aclImdb/train/neg')# 文件名列表
list_fileName_pos = file_name('./dataSet/aclImdb/train/pos')# 文件名列表
print('neg类有%d个样本'%len(list_fileName_neg))
print('pos类有%d个样本'%len(list_fileName_pos))

neg类有12500个样本
pos类有12500个样本


In [3]:
# 根据路径和文件名列表读取文件，用list存储
def get_list_fileData(file_dir=None, list_fileName = None):
    if file_dir is None or file_dir ==" ":
        print('文件路径为空')
        return None
    if list_fileName is None or list_fileName ==" ":
        print('文件名列表为空')
        return None
    fileData = []
    for file in list_fileName:
        with open(file_dir+file, encoding='utf-8') as f:
            fileData.append(f.read())
    return fileData

In [4]:
fileData_neg = get_list_fileData(file_dir='./dataSet/aclImdb/train/neg/', list_fileName = list_fileName_neg)
fileData_pos = get_list_fileData(file_dir='./dataSet/aclImdb/train/pos/', list_fileName = list_fileName_pos)
label_neg = list(['__label__%s'%'neg']*len(fileData_neg))
label_pos = list(['__label__%s'%'pos']*len(fileData_pos))

In [5]:
print(' ')

In [6]:
# 这一步及其消耗内存，随着数据量增加，飞速增长。实验时大概要6G。
from sklearn.feature_extraction.text import TfidfVectorizer
# 它将 CountVectorizer 和 TfidfTransformer 的所有选项组合在一个单例模型中
vectorizer = TfidfVectorizer()
train_feature = fileData_neg + fileData_pos
feature = vectorizer.fit_transform(train_feature).toarray()
print(feature.shape)

(25000, 74849)


In [7]:
import gc 
del  fileData_neg, fileData_pos， feature
gc.collect()

0

In [8]:
label = label_neg+label_pos

0

In [ ]:
import numpy as np
from pandas import DataFrame
from sklearn import svm
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split, cross_validate

# label 二值化
le = preprocessing.LabelEncoder()
laebl = le.fit_transform(label)

# 打乱样本顺序
feature = np.array(feature)
label = np.array(label)
feature, label = shuffle(feature, label, random_state=0)

# 数据划分
X_train, X_test, y_train, y_test = train_test_split(feature, label, test_size=0.33, random_state=42)

# 模型参数
clf = svm.SVC(C=1.0)

#交叉验证
cv_results = cross_validate(clf, feature, label, cv=3, return_train_score=False)
'''
# cv_results好像就是一个dict，应该可以直接使用DataFrame的
DataFrame(cv_results) # 加参数验证显示的顺序columns=['test_score','train_score','fit_time','score_time','estimator']
'''
df = {'测试得分':cv_reults['test_score'],
     '训练得分':cv_reults['train_score'],
     '拟合时间':cv_reults['fit_time'],
     '评估时间':cv_reults['score_time']}


#  clf.fit(feature, label)

In [ ]:
'''
学习曲线显示了不同数量的训练样本的估计器的验证和训练评分。
它可以帮助我们发现从增加更多的训 练数据中能获益多少，以及估计是否受到更多来自方差误差或偏差误差的影响。
如果在增加训练集大小时，验证分数和训练分数都收敛到一个很低的值，那么我们将不会从更多的训练数据中获益。
此时，增加训练样本将不会有太大作用。

如果训练样本的最大时，训练分数比验证分数得分大得多，那么增加训练样本很可能会增加泛化能力。
'''
import matplotlib.pyplot as plt
from sklearn.model_selection import learning_curve
from sklearn.model_selection import ShuffleSplit
def plot_learning_curve(estimator, title, X, y, ylim=None, cv=None,
                        n_jobs=None, train_sizes=np.linspace(.1, 1.0, 5)):
    """
    Generate a simple plot of the test and training learning curve.

    Parameters
    ----------
    estimator : object type that implements the "fit" and "predict" methods
        An object of that type which is cloned for each validation.

    title : string
        Title for the chart.

    X : array-like, shape (n_samples, n_features)
        Training vector, where n_samples is the number of samples and
        n_features is the number of features.

    y : array-like, shape (n_samples) or (n_samples, n_features), optional
        Target relative to X for classification or regression;
        None for unsupervised learning.

    ylim : tuple, shape (ymin, ymax), optional
        Defines minimum and maximum yvalues plotted.

    cv : int, cross-validation generator or an iterable, optional
        Determines the cross-validation splitting strategy.
        Possible inputs for cv are:
          - None, to use the default 3-fold cross-validation,
          - integer, to specify the number of folds.
          - :term:`CV splitter`,
          - An iterable yielding (train, test) splits as arrays of indices.

        For integer/None inputs, if ``y`` is binary or multiclass,
        :class:`StratifiedKFold` used. If the estimator is not a classifier
        or if ``y`` is neither binary nor multiclass, :class:`KFold` is used.

        Refer :ref:`User Guide <cross_validation>` for the various
        cross-validators that can be used here.

    n_jobs : int or None, optional (default=None)
        Number of jobs to run in parallel.
        ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
        ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
        for more details.

    train_sizes : array-like, shape (n_ticks,), dtype float or int
        Relative or absolute numbers of training examples that will be used to
        generate the learning curve. If the dtype is float, it is regarded as a
        fraction of the maximum size of the training set (that is determined
        by the selected validation method), i.e. it has to be within (0, 1].
        Otherwise it is interpreted as absolute sizes of the training sets.
        Note that for classification the number of samples usually have to
        be big enough to contain at least one sample from each class.
        (default: np.linspace(0.1, 1.0, 5))
    """
    plt.figure()
    plt.title(title)
    if ylim is not None:
        plt.ylim(*ylim)
    plt.xlabel("Training examples")
    plt.ylabel("Score")
    train_sizes, train_scores, test_scores = learning_curve(
        estimator, X, y, cv=cv, n_jobs=n_jobs, train_sizes=train_sizes)
    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)
    plt.grid()

    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, alpha=0.1,
                     color="r")
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, alpha=0.1, color="g")
    plt.plot(train_sizes, train_scores_mean, 'o-', color="r",
             label="Training score")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g",
             label="Cross-validation score")

    plt.legend(loc="best")
    return plt

# 测试该函数
title = "Learning Curves (SVM, RBF kernel, $\gamma=0.001$)"
# SVC is more expensive so we do a lower number of CV iterations:
cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)
estimator = SVC(gamma=0.001)
plot_learning_curve(estimator, title, X, y, (0.7, 1.01), cv=cv, n_jobs=4)

plt.show()