In [ ]:
1. 文件读取 
2. 特征提取
3. 分类算法，svm,RF,
4. 绘图PR，AUC，训练曲线与测试曲线，学习曲线与验证曲线
5. 指标acc,presion,recall,自定义的误判率和漏判率

In [1]:
from sklearn.feature_extraction import DictVectorizer
# 将dict转成numpy。采用了对同一个key采用了ont-hot，数值型values保留原类型
measurements = [
    {'city': 'Dubai', 'temperature': 33.},
    {'city': 'London', 'temperature': 12.},
    {'city': 'San Francisco', 'temperature': 18.},
] 

vec = DictVectorizer()
print(vec.fit_transform(measurements).toarray(), '\n')
print('city有三个字符型的值，one-hot后有三列;temperature数值型，保留，所以共有4列','\n')
print(vec.get_feature_names(), '\n')
print('通过此方法获得one-hot后，每列所对应的原本的值')

[[ 1.  0.  0. 33.]
 [ 0.  1.  0. 12.]
 [ 0.  0.  1. 18.]] 

city有三个字符型的值，one-hot后有三列;temperature数值型，保留，所以共有4列 

['city=Dubai', 'city=London', 'city=San Francisco', 'temperature'] 

通过此方法获得one-hot后，每列所对应的原本的值


# from sklearn.feature_extraction.text import CountVectorizer
- 实现了 tokenization （词语切分,包括n-gram）和 occurrence counting （出现频数统计）,TF-IDF
- 这个模型有很多参数，但参数的默认初始值是相当合理的。查看文档获取

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
# 实现了 tokenization （词语切分,包括n-gram,停用词）和 occurrence counting （出现频数统计）,TF-IDF
# 这个模型有很多参数，但参数的默认初始值是相当合理的。查看文档获取

In [3]:
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]

In [4]:
vectorizer = CountVectorizer()
#bigram_vectorizer = CountVectorizer(ngram_range=(1, 2),
#                                    token_pattern=r'\b\w+\b', min_df=1) # 提取n-gram
X = vectorizer.fit_transform(corpus)
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [5]:
X.toarray() # 词袋结果, 注意第二行有个2 ，说明了该方法是统计了词频的

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [6]:
vectorizer.vocabulary_ # 查看单词对应索引
vectorizer.vocabulary_.get('xxx') # 指定获取某一单词的所有

# TfidfTransformer

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer

In [8]:
transformer = TfidfTransformer(smooth_idf=False)

counts = [[3, 0, 1],
          [2, 0, 0],
          [3, 0, 0],
          [4, 0, 0],
          [3, 2, 0],
          [3, 0, 2]]

tfidf = transformer.fit_transform(counts)
tfidf.toarray() 

array([[0.81940995, 0.        , 0.57320793],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.47330339, 0.88089948, 0.        ],
       [0.58149261, 0.        , 0.81355169]])

# TfidfVectorizer

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
# 它将 CountVectorizer 和 TfidfTransformer 的所有选项组合在一个单例模型中
vectorizer = TfidfVectorizer()

corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]

vectorizer.fit_transform(corpus).toarray()

array([[0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674],
       [0.        , 0.27230147, 0.        , 0.27230147, 0.        ,
        0.85322574, 0.22262429, 0.        , 0.27230147],
       [0.55280532, 0.        , 0.        , 0.        , 0.55280532,
        0.        , 0.28847675, 0.55280532, 0.        ],
       [0.        , 0.43877674, 0.54197657, 0.43877674, 0.        ,
        0.        , 0.35872874, 0.        , 0.43877674]])

# SVM

In [30]:
from sklearn import svm

X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC(C=1.0)
clf.fit(X, y)
clf.predict([[2., 2.]])

array([1])

In [ ]:
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [1]:
import os  
      
def file_name(file_dir):   
    for root, dirs, files in os.walk(file_dir):  
        #print(root) #当前目录路径  
        #print(dirs) #当前路径下所有子目录  
        return files #当前路径下所有非目录子文件

In [2]:
list_fileName_neg = file_name('./dataSet/aclImdb/train/neg')# 文件名列表
list_fileName_pos = file_name('./dataSet/aclImdb/train/pos')# 文件名列表
print('neg类有%d个样本'%len(list_fileName_neg))
print('pos类有%d个样本'%len(list_fileName_pos))

neg类有12500个样本
pos类有12500个样本


In [3]:
# 根据路径和文件名列表读取文件，用list存储
def get_list_fileData(file_dir=None, list_fileName = None):
    if file_dir is None or file_dir ==" ":
        print('文件路径为空')
        return None
    if list_fileName is None or list_fileName ==" ":
        print('文件名列表为空')
        return None
    fileData = []
    for file in list_fileName:
        with open(file_dir+file, encoding='utf-8') as f:
            fileData.append(f.read())
    return fileData

In [4]:
fileData_neg = get_list_fileData(file_dir='./dataSet/aclImdb/train/neg/', list_fileName = list_fileName_neg)
fileData_pos = get_list_fileData(file_dir='./dataSet/aclImdb/train/pos/', list_fileName = list_fileName_pos)
label_neg = list(['__label__%s'%'neg']*len(fileData_neg))
label_pos = list(['__label__%s'%'pos']*len(fileData_pos))

In [5]:
print(' ')

In [6]:
# 这一步及其消耗内存，随着数据量增加，飞速增长。实验时大概要6G。
from sklearn.feature_extraction.text import TfidfVectorizer
# 它将 CountVectorizer 和 TfidfTransformer 的所有选项组合在一个单例模型中
vectorizer = TfidfVectorizer()
train_feature = fileData_neg + fileData_pos
feature = vectorizer.fit_transform(train_feature).toarray()
print(feature.shape)

(25000, 74849)


In [7]:
import gc 
del vectorizer, fileData_neg, fileData_pos
gc.collect()
# 少3G内存

0

In [8]:
del feature
gc.collect()
# 少2G内存

0